version: '0.1'

services:
  web:
    image: php:7.1.3
    ports:
      - 80:80
    volumes:
      - './ismesoft:/var/www/html'
    links:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      -  8000:80
    links:
      - db:db
      
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
  
